_packs = [
// Ace gunbags
  "ace_gunbag",
  "ace_gunbag_tan",

// Vanilla
  "B_Carryall_cbr",
  "B_Carryall_oli",
  "B_Kitbag_cbr",
  "B_Kitbag_rgr",
  "B_Kitbag_tan,"
  "B_AssaultPack_rgr",
  "B_AssaultPack_cbr",
  "B_Assaultpack_KHK",

// RHS + Modified
 /* "MRB_assault_eagleaiii_coy_Medic",
  "rhsusf_assault_eagleaiii_coy",
  "B_rhsusf_B_BACKPACK",*/

// MILGP BackPacks
  "milgp_bp_Breacher_cb",
  "milgp_bp_hydration_cb",
  "milgp_bp_Pointman_cb",
  "milgp_bp_Tomahawk_cb",

//VSM
  "VSM_OGA_OD_carryall",
  "VSM_OGA_OD_Backpack_Compact",
  "VSM_OGA_OD_Backpack_Kitbag",

// COS Backpacks
  "COS_PARACHUTE",
  "PARACHUTE_W",
  "drybag_blk",
  "drybag_od",
  "KIT_BAG_alpin_OD",
  "KIT_BAG_alpin_TAN",
  "KIT_BAG_od",
  "KIT_BAG_TAN",
  "KIT_BAG_pince_od",
  "KIT_BAG_pince_TAN",
  "KIT_BAG_R_od",
  "KIT_BAG_R_TAN",
  "SOG_BAG_BREACHER_od",
  "SOG_BAG_BREACHER_tan",
  "SOG_BAG_ALPINE_od",
  "SOG_BAG_ALPINE_tan",
  "SOG_BAG_med_od",
  "SOG_BAG_med_tan",
  "SOG_BAG_OD",
  "SOG_BAG_recon_od",
  "SOG_BAG_recon_tan",
  "SOG_BAG_tan",
	
//USP
  "USP_PACK_BREACHER_CBR",
  "USP_PACK_FASTHAWK",
  "USP_PACK_HYDRATION",
  "USP_PACK_POINTMAN",
  "USP_45L_RUCKSACK_GRN",
  "USP_45L_RUCKSACK_MC",
  "USP_TACTICAL_PACK",
  "USP_TACTICAL_PACK_MCT",
  "USP_TACTICAL_PACK_CCT",
  "USP_TACTICAL_PACK_MCT_CCT2",
  "USP_TACTICAL_PACK_CCT2",
  "USP_TACTICAL_PACK_MCT_CCT3",
  "USP_TACTICAL_PACK_CCT3",
  "USP_TACTICAL_PACK_MCT_CCT4",
  "USP_TACTICAL_PACK_CCT4",
  "USP_TACTICAL_PACK_MCT_CCT5",
  "USP_TACTICAL_PACK_CCT5",
  "USP_TACTICAL_PACK_MCT_CCT6",
  "USP_TACTICAL_PACK_CCT6",
  "USP_TACTICAL_PACK_MCT_CCT7",	
  "USP_TACTICAL_PACK_CCT7",
  "USP_TACTICAL_PACK_MCT_CCT8",
  "USP_TACTICAL_PACK_CCT8",
  "USP_HYDRATION_PACK_CBR",
  "USP_HYDRATION_PACK_RGR",
  "USP_REEBOW_3DAP_MC",
  "USP_REEBOW_3DAP_MCT",
  "USP_REEBOW_3DAP_ACC1_MC",
  "USP_REEBOW_3DAP_ACC1_MCT",
  "USP_REEBOW_3DAP_ACC10_MC",
  "USP_REEBOW_3DAP_ACC10_MCT",
  "USP_REEBOW_3DAP_ACC2_MC",
  "USP_REEBOW_3DAP_ACC2_MCT",
  "USP_REEBOW_3DAP_ACC3_MC",
  "USP_REEBOW_3DAP_ACC3_MCT",
  "USP_REEBOW_3DAP_ACC4_MC",
  "USP_REEBOW_3DAP_ACC4_MCT",
  "USP_REEBOW_3DAP_ACC5_MC",
  "USP_REEBOW_3DAP_ACC5_MCT",
  "USP_REEBOW_3DAP_ACC6_MC",
  "USP_REEBOW_3DAP_ACC6_MCT",
  "USP_REEBOW_3DAP_ACC7_MC",
  "USP_REEBOW_3DAP_ACC7_MCT",
  "USP_REEBOW_3DAP_ACC8_MC",
  "USP_REEBOW_3DAP_ACC8_MCT",
  "USP_REEBOW_3DAP_ACC9_MC",
  "USP_REEBOW_3DAP_ACC9_MCT",
  "USP_DELTA_BAG_MC",
  "USP_DELTA_BAG_M81",
  "USP_HYDROPACK_MC",
  "USP_HYDROPACK_RGR"
	
];
