_headgear = [
//MilGp High-Cuts
"milgp_h_opscore_01_khk_cb",
"milgp_h_opscore_01_khk_cb_mcc",
"milgp_h_opscore_01_khk_cb_mcalc",
"milgp_h_opscore_01_goggles_khk_cb",
"milgp_h_opscore_01_goggles_khk_cb_mcc",
"milgp_h_opscore_01_goggles_khk_cb_mcalc",

"milgp_h_opscore_02_khk_cb",
"milgp_h_opscore_02_khk_cb_mcc",
"milgp_h_opscore_02_khk_cb_mcalc",
"milgp_h_opscore_02_goggles_khk_cb",
"milgp_h_opscore_02_goggles_khk_cb_mcc",
"milgp_h_opscore_02_goggles_khk_cb_mcalc",

"milgp_h_opscore_03_khk_cb",
"milgp_h_opscore_03_khk_cb_mcc",
"milgp_h_opscore_03_khk_cb_mcalc",
"milgp_h_opscore_03_goggles_khk_cb",
"milgp_h_opscore_03_goggles_khk_cb_mcc",
"milgp_h_opscore_03_goggles_khk_cb_mcalc",

"milgp_h_opscore_04_khk_cb",
"milgp_h_opscore_04_khk_cb_mcc",
"milgp_h_opscore_04_khk_cb_mcc",
"milgp_h_opscore_04_khk_cb_mcalc",
"milgp_h_opscore_04_goggles_khk_cb",
"milgp_h_opscore_04_goggles_khk_cb_mcc",
"milgp_h_opscore_04_goggles_khk_cb_mcalc",

"milgp_h_opscore_05_khk_cb",
"milgp_h_opscore_05_khk_cb_mcc",
"milgp_h_opscore_05_khk_cb_mcalc",
"milgp_h_opscore_05_goggles_khk_cb",
"milgp_h_opscore_05_goggles_khk_cb_mcc",
"milgp_h_opscore_05_goggles_khk_cb_mcalc",

"milgp_h_opscore_06_khk_cb",
"milgp_h_opscore_06_khk_cb_mcc",
"milgp_h_opscore_06_khk_cb_mcalc",
"milgp_h_opscore_06_goggles_khk_cb",
"milgp_h_opscore_06_goggles_khk_cb_mcc",
"Milgp_h_opscore_06_goggles_khk_cb_mcalc",

"milgp_h_opscore_01_khk_rgr",
"milgp_h_opscore_01_khk_rgr_mcc",
"milgp_h_opscore_01_khk_rgr_mcalc",
"milgp_h_opscore_01_goggles_khk_rgr",
"milgp_h_opscore_01_goggles_khk_rgr_mcc",
"milgp_h_opscore_01_goggles_khk_rgr_mcalc",

"milgp_h_opscore_02_khk_rgr",
"milgp_h_opscore_02_khk_rgr_mcc",
"milgp_h_opscore_02_khk_rgr_mcalc",
"milgp_h_opscore_02_goggles_khk_rgr",
"milgp_h_opscore_02_goggles_khk_rgr_mcc",
"milgp_h_opscore_02_goggles_khk_rgr_mcalc",

"milgp_h_opscore_03_khk_rgr",
"milgp_h_opscore_03_khk_rgr_mcc",
"milgp_h_opscore_03_khk_rgr_mcalc",
"milgp_h_opscore_03_goggles_khk_rgr",
"milgp_h_opscore_03_goggles_khk_rgr_mcc",
"milgp_h_opscore_03_goggles_khk_rgr_mcalc",

"milgp_h_opscore_04_khk_rgr",
"milgp_h_opscore_04_khk_rgr_mcc",
"milgp_h_opscore_04_khk_rgr_mcc",
"milgp_h_opscore_04_khk_rgr_mcalc",
"milgp_h_opscore_04_goggles_khk_rgr",
"milgp_h_opscore_04_goggles_khk_rgr_mcc",
"milgp_h_opscore_04_goggles_khk_rgr_mcalc",

"milgp_h_opscore_05_khk_rgr",
"milgp_h_opscore_05_khk_rgr_mcc",
"milgp_h_opscore_05_khk_rgr_mcalc",
"milgp_h_opscore_05_goggles_khk_rgr",
"milgp_h_opscore_05_goggles_khk_rgr_mcc",
"milgp_h_opscore_05_goggles_khk_rgr_mcalc",

"milgp_h_opscore_06_khk_rgr",
"milgp_h_opscore_06_khk_rgr_mcc",
"milgp_h_opscore_06_khk_rgr_mcalc",
"milgp_h_opscore_06_goggles_khk_rgr",
"milgp_h_opscore_06_goggles_khk_rgr_mcc",
"milgp_h_opscore_06_goggles_khk_rgr_mcalc",

//Softcovers
"rhs_booniehat2_marpatd",
"rhs_booniehat2_marpatwd",
"rhssaf_booniehat_woodland",
"H_Booniehat_khk_hs",
"rhs_8point_marpatd",
"rhs_8point_marpatwd",
"milgp_h_cap_01_blk_blk",
"milgp_h_cap_01_cb_cb",
"milgp_h_cap_01_gry_blk",
"milgp_h_cap_01_khk_khk",
"milgp_h_cap_01_m81_cb",
"milgp_h_cap_01_mc_cb",
"milgp_h_cap_01_rgr_rgr",
"milgp_h_cap_01_tan_khk",
"milgp_h_cap_backwards_01_blk_blk",
"milgp_h_cap_backwards_01_cb_cb",
"milgp_h_cap_backwards_01_gry_cb",
"milgp_h_cap_backwards_01_khk_khk",
"milgp_h_cap_backwards_01_m81_rgr",
"milgp_h_cap_backwards_01_mc_cb",
"milgp_h_cap_backwards_01_rgr_rgr",
"milgp_h_cap_backwards_01_tan_khk",

"SOAS_160th_Beret_1stLT",
"SOAS_160th_Beret_2ndLT",
"SOAS_160th_Beret_CPT",
"SOAS_160th_Beret_CW2",
"SOAS_160th_Beret_CW3",
"SOAS_160th_Beret_CW4",
"SOAS_160th_Beret_CW5",
"SOAS_160th_Beret_e",
"SOAS_160th_Beret_LTC",
"SOAS_160th_Beret_MAJ",
"SOAS_160th_Beret_WO1",

//Aviation Headgear
"rhsusf_hgu56p_black",
"rhsusf_hgu56p_mask_black",
"rhsusf_hgu56p_mask_black_skull",
"rhsusf_hgu56p_visor_black",
"rhsusf_hgu56p_visor_mask_black",
"rhsusf_hgu56p_visor_mask_Empire_black",
"rhsusf_hgu56p_visor_mask_black_skull",
"rhsusf_hgu56p_green",
"rhsusf_hgu56p_mask_green",
"rhsusf_hgu56p_mask_green_mo",
"rhsusf_hgu56p_visor_green",
"rhsusf_hgu56p_visor_mask_green",
"rhsusf_hgu56p_visor_mask_green_mo",
"rhsusf_hgu56p",
"rhsusf_hgu56p_mask",
"rhsusf_hgu56p_mask_mo",
"rhsusf_hgu56p_mask_skull",
"rhsusf_hgu56p_visor",
"rhsusf_hgu56p_visor_mask",
"rhsusf_hgu56p_visor_mask_mo",
"rhsusf_hgu56p_visor_mask_skull",
"rhsusf_hgu56p_white",
"rhsusf_hgu56p_visor_white",
"MRB_H_hgu56_Carrera",
"MRB_H_hgu56_visor_Brueske",
"MRB_H_hgu56_visor_Levorse",
"MRB_H_hgu56_visor_mask_Whelan",

"RHS_jetpilot_usaf",
"JS_JC_FA18_PilotHelmet",

//Tuuli Headgear
"MRB_H_hgu56_visor_mask_Tuulessa",
"MRB_H_hgu56_visor_mask_Murda"

];
