_uniforms = [

//FIR Uniforms
    "FIR_Fighter_Pilot_Nomex",
    "FIR_Fighter_Pilot_Nomex2",
    "FIR_Fighter_Pilot_Nomex3",
    "FIR_Fighter_Pilot_Nomex4",
    "FIR_Fighter_Pilot_Nomex5",
    "FIR_Fighter_Pilot_Nomex6",
    "FIR_Fighter_Pilot_Nomex7",

// 160th SOAR uniforms
	"RHS_Uniform_ABU",

// Chemical Warfare
	"U_B_CBRN",

// Uniforms
    "U_B_HeliPilotCoveralls",
    "U_B_Wetsuit",
    "U_B_survival_uniform",

// SOCOM Uniforms
    //"SOCOM_uniform_g3_m81_base",
    "SOCOM_uniform_g3_dcu_base",
    "milgp_u_fleece_grey_g3_field_pants_M81",

// Civilian vanilla
	"U_BG_Guerilla_6_1",
	"U_BG_Guerilla_2_2",
	"U_BG_Guerilla2_1",
	"U_BG_Guerilla2_3",
	"U_Marshal",
	"U_C_Man_Casual_2_F",
	"U_C_Man_Casual_3_F",
	"U_C_Man_Casual_1_F",
//VSM
	"VSM_AOR1_Crye_grey_pants_Camo",
	"VSM_AOR1_Crye_grey_shirt_Camo",
	"VSM_AOR1_Crye_od_pants_Camo",
	"VSM_AOR1_Crye_od_shirt_Camo",
	"VSM_AOR1_Crye_tan_pants_Camo",
	"VSM_AOR1_Crye_tan_shirt_Camo",
	"VSM_AOR1_Crye_Camo",
	"VSM_M81_Crye_grey_pants_Camo",
	"VSM_M81_Crye_grey_shirt_Camo",
	"VSM_M81_Crye_od_pants_Camo",
	"VSM_M81_Crye_od_shirt_Camo",
	"VSM_M81_Crye_tan_pants_Camo",
	"VSM_M81_Crye_tan_shirt_Camo",
	"VSM_M81_Crye_Camo",
	"VSM_Multicam_Crye_grey_pants_Camo",
	"VSM_Multicam_Crye_grey_shirt_Camo",
	"VSM_Multicam_Crye_od_pants_Camo",
	"VSM_Multicam_Crye_od_shirt_Camo",
	"VSM_Multicam_Crye_tan_pants_Camo",
	"VSM_Multicam_Crye_tan_shirt_Camo",
	"VSM_Multicam_Crye_Camo",
	"VSM_AOR1_Crye_SS_grey_pants_Camo",
	"VSM_AOR1_Crye_SS_grey_shirt_Camo",
	"VSM_AOR1_Crye_SS_od_pants_Camo",
	"VSM_AOR1_Crye_SS_od_shirt_Camo",
	"VSM_AOR1_Crye_SS_tan_pants_Camo",
	"VSM_AOR1_Crye_SS_tan_shirt_Camo",
	"VSM_AOR1_Crye_SS_Camo",
	"VSM_M81_Crye_SS_grey_pants_Camo",
	"VSM_M81_Crye_SS_grey_shirt_Camo",
	"VSM_M81_Crye_SS_od_pants_Camo",
	"VSM_M81_Crye_SS_od_shirt_Camo",
	"VSM_M81_Crye_SS_tan_pants_Camo",
	"VSM_M81_Crye_SS_tan_shirt_Camo",
	"VSM_M81_Crye_SS_Camo",
	"VSM_OGA_Crye_Camo",
	"VSM_Multicam_Crye_SS_grey_pants_Camo",
	"VSM_Multicam_Crye_SS_grey_shirt_Camo",
	"VSM_Multicam_Crye_SS_od_pants_Camo",
	"VSM_Multicam_Crye_SS_od_shirt_Camo",
	"VSM_Multicam_Crye_SS_tan_pants_Camo",
	"VSM_Multicam_Crye_SS_tan_shirt_Camo",
	"VSM_Multicam_Crye_SS_Camo",
	"VSM_AOR1_Crye_Tee_Camo",
	"VSM_M81_Crye_Tee_Camo",
	"VSM_Multicam_Crye_Tee_Camo",
	"Alpine_Crye_Camo",
	"Alpine_Crye_SS_Camo",
	"Milgp_u_fleece_grey_g3_field_pants_mcalpine",
	"Mligp_u_g3_field_set_mcalpine",
	"milgp_u_pcu_g3_field_pants_mcalpine",
	"black_Crye_Camo",
	"Black_Crye_SS_Camo",
	"VSM_AOR1_casual_Camo",
	"VSM_M81_casual_Camo",
	"VSM_Multicam_casual_Camo",
	"Multicam_Alpine_casual_Camo",
	"Multicam_black_casual_Camo",
	"Multicam_Olive_casual_Camo",
	"Multicam_Tan_casual_Camo",
	"VSM_OGA_grey_casual_Camo",
	"VSM_OGA_OD_casual_Camo",
	"VSM_OGA_tan_casual_Camo",
//RHS
	"rhs_uniform_FROG01_wd",
	"rhs_uniform_FROG01_d"
];