_vests = [
// Vests
	"V_TacVest_oli",
	"V_RebreatherB",

// FIR Vests
	"FIR_pilot_vest",
	"FIR_saftyvest_yellow",
	"FIR_saftyvest_orange",
	
//VSM
	"VSM_FAPC_Breacher_AOR1",
	"VSM_FAPC_MG_AOR1",
	"VSM_FAPC_Operator_AOR1",
	"VSM_CarrierRig_Breacher_AOR1",
	"VSM_CarrierRig_Gunner_AOR1",
	"VSM_CarrierRig_Operator_AOR1",
	"VSM_LBT6094_breacher_AOR1",
	"VSM_LBT6094_MG_AOR1",
	"VSM_LBT6094_operator_AOR1",
	"VSM_RAV_Breacher_AOR1",
	"VSM_RAV_MG_AOR1",
	"VSM_RAV_operator_AOR1",
	"VSM_FAPC_Breacher_M81",
	"VSM_FAPC_MG_M81",
	"VSM_FAPC_Operator_M81",
	"VSM_CarrierRig_Breacher_M81",
	"VSM_CarrierRig_Gunner_M81",
	"VSM_CarrierRig_Operator_M81",
	"VSM_LBT6094_breacher_M81",
	"VSM_LBT6094_MG_M81",
	"VSM_LBT6094_operator_M81",
	"VSM_RAV_Breacher_M81",
	"VSM_RAV_MG_M81",
	"VSM_RAV_operator_M81",
	"VSM_FAPC_Breacher_Multicam",
	"VSM_FAPC_MG_Multicam",
	"VSM_FAPC_Operator_Multicam",
	"VSM_CarrierRig_Breacher_Multicam",
	"VSM_CarrierRig_Gunner_Multicam",
	"VSM_CarrierRig_Operator_Multicam",
	"VSM_LBT6094_breacher_Multicam",
	"VSM_LBT6094_MG_Multicam",
	"VSM_LBT6094_operator_Multicam",
	"VSM_RAV_Breacher_Multicam",
	"VSM_RAV_MG_Multicam",
	"VSM_RAV_operator_Multicam",
	"VSM_FAPC_Breacher_OGA",
	"VSM_FAPC_MG_OGA",
	"VSM_FAPC_Operator_OGA",
	"VSM_CarrierRig_Breacher_OGA",
	"VSM_CarrierRig_Gunner_OGA",
	"VSM_CarrierRig_Operator_OGA",
	"VSM_LBT6094_breacher_OGA",
	"VSM_LBT6094_MG_OGA",
	"VSM_LBT6094_operator_OGA",
	"VSM_FAPC_Breacher_OGA_OD",
	"VSM_FAPC_MG_OGA_OD",
	"VSM_FAPC_Operator_OGA_OD",
	"VSM_CarrierRig_Breacher_OGA_OD",
	"VSM_CarrierRig_Gunner_OGA_OD",
	"VSM_CarrierRig_Operator_OGA_OD",
	"VSM_LBT6094_breacher_OGA_OD",
	"VSM_LBT6094_MG_OGA_OD",
	"VSM_LBT6094_operator_OGA_OD",
	"VSM_RAV_Breacher_OGA_OD",
	"VSM_RAV_MG_OGA_OD",
	"VSM_RAV_operator_OGA_OD",
	"VSM_RAV_Breacher_OGA",
	"VSM_RAV_MG_OGA",
	"VSM_RAV_operator_OGA",
	"VSM_OGA_Vest_1",
	"VSM_OGA_OD_Vest_1",
	"VSM_OGA_Vest_2",
	"VSM_OGA_OD_Vest_2",
	"VSM_OGA_Vest_3",
	"VSM_OGA_OD_Vest_3",
	"dr_Alpinefacp_br",
	"dr_Alpinefacp_mg",
	"dr_Alpinefacp_op",
	"dr_Alpinelbt_br",
	"dr_Alpinelbt_mg",
	"dr_Alpinelbt_op",
	"dr_Alpinepar_br",
	"dr_Alpinepar_mg",
	"dr_Alpinepar_op",
	"LBT_1961_Alpine",
	"dr_BLKfacp_br",
	"dr_BLKfacp_mg",
	"dr_BLKfacp_op",
	"dr_BLKlbt_br",
	"dr_BLKlbt_mg",
	"dr_BLKlbt_op",
	"dr_BLKpar_br",
	"dr_BLKpar_mg",
	"dr_BLKpar_op",
	"CarrieRrig_Breacher_Alpine",
	"CarrieRrig_Gunner_Alpine",
	"CarrieRrig_Operator_Alpine",

// MILGP Vests / Uniforms
	// MILGP Fleece
	"milgp_u_fleece_grey_g3_field_pants_3CD",
	"milgp_u_fleece_grey_g3_field_pants_khk",
	"milgp_u_fleece_grey_g3_field_pants_rgr",
	"milgp_u_fleece_grey_g3_field_pants_M81",
	"milgp_u_fleece_khk_g3_field_pants_khk",
	"milgp_u_fleece_khk_g3_field_pants_3CD",
	"milgp_u_fleece_rgr_g3_field_pants_rgr",
	"milgp_u_fleece_rgr_g3_field_pants_M81",

	//MILGP Field Set Rolled
	"milgp_u_g3_field_set_rolled_khk",
	"milgp_u_g3_field_set_rolled_m81",
	"milgp_u_g3_field_set_rolled_rgr",
	
	// MILGP JPC Assaulter
	"milgp_v_jpc_assaulter_belt_cb",
	"milgp_v_jpc_assaulter_belt_khk",
	"milgp_v_jpc_assaulter_belt_mc",
	"milgp_v_jpc_assaulter_belt_rgr",
	"milgp_v_jpc_assaulter_cb",
	"milgp_v_jpc_assaulter_khk",
	"milgp_v_jpc_assaulter_mc",
	"milgp_v_jpc_assaulter_rgr",
	
	// MILGP JPC Grenadier
	"milgp_v_jpc_Grenadier_belt_cb",
	"milgp_v_jpc_Grenadier_belt_khk",
	"milgp_v_jpc_Grenadier_belt_mc",
	"milgp_v_jpc_Grenadier_belt_rgr",
	"milgp_v_jpc_Grenadier_cb",
	"milgp_v_jpc_Grenadier_khk",
	"milgp_v_jpc_Grenadier_mc",
	"milgp_v_jpc_Grenadier_rgr",
	
	// MILGP JPC Heavy Gunner
	"milgp_v_jpc_hgunner_belt_cb",
	"milgp_v_jpc_hgunner_belt_khk",
	"milgp_v_jpc_hgunner_belt_mc",
	"milgp_v_jpc_hgunner_belt_rgr",
	"milgp_v_jpc_hgunner_cb",
	"milgp_v_jpc_hgunner_khk",
	"milgp_v_jpc_hgunner_mc",
	"milgp_v_jpc_hgunner_rgr",
	
	// MILGP JPC Marksman
	"milgp_v_jpc_marksman_belt_cb",
	"milgp_v_jpc_marksman_belt_khk",
	"milgp_v_jpc_marksman_belt_mc",
	"milgp_v_jpc_marksman_belt_rgr",
	"milgp_v_jpc_Marksman_cb",
	"milgp_v_jpc_Marksman_khk",
	"milgp_v_jpc_Marksman_mc",
	"milgp_v_jpc_Marksman_rgr",
	
	// MILGP JPC Medic
	"milgp_v_jpc_medic_belt_cb",
	"milgp_v_jpc_medic_belt_khk",
	"milgp_v_jpc_medic_belt_mc",
	"milgp_v_jpc_medic_belt_rgr",
	"milgp_v_jpc_Medic_cb",
	"milgp_v_jpc_Medic_khk",
	"milgp_v_jpc_Medic_mc",
	"milgp_v_jpc_Medic_rgr",
	
	// MILGP JPC Teamleader
	"milgp_v_jpc_teamleader_belt_cb",
	"milgp_v_jpc_teamleader_belt_khk",
	"milgp_v_jpc_teamleader_belt_mc",
	"milgp_v_jpc_teamleader_belt_rgr",
	"milgp_v_jpc_TeamLeader_cb",
	"milgp_v_jpc_TeamLeader_khk",
	"milgp_v_jpc_TeamLeader_mc",
	"milgp_v_jpc_TeamLeader_rgr",
	
	// Marciras MILGP Assaulter
	"milgp_v_marciras_assaulter_belt_cb",
	"milgp_v_marciras_assaulter_belt_khk",
	"milgp_v_marciras_assaulter_belt_mc",
	"milgp_v_marciras_assaulter_belt_rgr",
	"milgp_v_marciras_assaulter_cb",
	"milgp_v_marciras_assaulter_khk",
	"milgp_v_marciras_assaulter_mc",
	"milgp_v_marciras_assaulter_rgr",
	
	// MilGP Marciras Grenadier
	"milgp_v_marciras_grenadier_belt_cb",
	"milgp_v_marciras_grenadier_belt_khk",
	"milgp_v_marciras_grenadier_belt_mc",
	"milgp_v_marciras_grenadier_belt_rgr",
	"milgp_v_marciras_grenadier_cb",
	"milgp_v_marciras_grenadier_khk",
	"milgp_v_marciras_grenadier_mc",
	"milgp_v_marciras_grenadier_rgr",
	
	// MilGP Marciras Heavy Gunner
	"milgp_v_marciras_hgunner_belt_cb",
	"milgp_v_marciras_hgunner_belt_khk",
	"milgp_v_marciras_hgunner_belt_mc",
	"milgp_v_marciras_hgunner_belt_rgr",
	"milgp_v_marciras_hgunner_cb",
	"milgp_v_marciras_hgunner_khk",
	"milgp_v_marciras_hgunner_mc",
	"milgp_v_marciras_hgunner_rgr",
	
	// MilGP Marciras Marksman
	"milgp_v_marciras_marksman_belt_cb",
	"milgp_v_marciras_marksman_belt_khk",
	"milgp_v_marciras_marksman_belt_mc",
	"milgp_v_marciras_marksman_belt_rgr",
	"milgp_v_marciras_marksman_cb",
	"milgp_v_marciras_marksman_khk",
	"milgp_v_marciras_marksman_mc",
	"milgp_v_marciras_marksman_rgr",
	
	// MilGP Marciras Medic
	"milgp_v_marciras_medic_belt_cb",
	"milgp_v_marciras_medic_belt_khk",
	"milgp_v_marciras_medic_belt_mc",
	"milgp_v_marciras_medic_belt_rgr",
	"milgp_v_marciras_medic_cb",
	"milgp_v_marciras_medic_khk",
	"milgp_v_marciras_medic_mc",
	"milgp_v_marciras_medic_rgr",
	
	// MilGP Marciras Teamleader
	"milgp_v_marciras_teamleader_belt_CB",
	"milgp_v_marciras_teamleader_belt_KHK",
	"milgp_v_marciras_teamleader_belt_mc",
	"milgp_v_marciras_teamleader_belt_RGR",
	"milgp_v_marciras_teamleader_CB",
	"milgp_v_marciras_teamleader_KHK",
	"milgp_v_marciras_teamleader_mc",
	"milgp_v_marciras_teamleader_RGR",

	//MilGP MMAC Assaulter
	"milgp_v_mmac_assaulter_belt_CB",
	"milgp_v_mmac_assaulter_belt_KHK",
	"milgp_v_mmac_assaulter_belt_MC",
	"milgp_v_mmac_assaulter_belt_rgr",
	"milgp_v_mmac_assaulter_CB",
	"milgp_v_mmac_assaulter_KHK",
	"milgp_v_mmac_assaulter_MC",
	"milgp_v_mmac_assaulter_rgr",

	//MilGP MMAC Grenadier
	"milgp_v_mmac_grenadier_belt_CB",
	"milgp_v_mmac_grenadier_belt_KHK",
	"milgp_v_mmac_grenadier_belt_MC",
	"milgp_v_mmac_grenadier_belt_rgr",
	"milgp_v_mmac_grenadier_CB",
	"milgp_v_mmac_grenadier_KHK",
	"milgp_v_mmac_grenadier_MC",
	"milgp_v_mmac_grenadier_rgr",

	//MilGP MMAC Heavy Gunner
	"milgp_v_mmac_hgunner_belt_CB",
	"milgp_v_mmac_hgunner_belt_KHK",
	"milgp_v_mmac_hgunner_belt_MC",
	"milgp_v_mmac_hgunner_belt_rgr",
	"milgp_v_mmac_hgunner_CB",
	"milgp_v_mmac_hgunner_KHK",
	"milgp_v_mmac_hgunner_MC",
	"milgp_v_mmac_hgunner_rgr",

	//MilGP MMAC Marksman
	"milgp_v_mmac_marksman_belt_CB",
	"milgp_v_mmac_marksman_belt_KHK",
	"milgp_v_mmac_marksman_belt_MC",
	"milgp_v_mmac_marksman_belt_rgr",
	"milgp_v_mmac_marksman_CB",
	"milgp_v_mmac_marksman_KHK",
	"milgp_v_mmac_marksman_MC",
	"milgp_v_mmac_marksman_rgr",

	//MilGP MMAC Medic
	"milgp_v_mmac_medic_belt_CB",
	"milgp_v_mmac_medic_belt_KHK",
	"milgp_v_mmac_medic_belt_MC",
	"milgp_v_mmac_medic_belt_rgr",
	"milgp_v_mmac_medic_CB",
	"milgp_v_mmac_medic_KHK",
	"milgp_v_mmac_medic_MC",
	"milgp_v_mmac_medic_rgr",

	//MilGP MMAC Team Leader
	"milgp_v_mmac_teamleader_belt_CB",
	"milgp_v_mmac_teamleader_belt_KHK",
	"milgp_v_mmac_teamleader_belt_MC",
	"milgp_v_mmac_teamleader_belt_rgr",
	"milgp_v_mmac_teamleader_CB",
	"milgp_v_mmac_teamleader_KHK",
	"milgp_v_mmac_teamleader_MC",
	"milgp_v_mmac_teamleader_rgr"
];
