_vests = [
// Vests
	"V_TacVest_oli",
	"V_RebreatherB",

// FIR Vests
	"FIR_pilot_vest",
	"FIR_saftyvest_yellow",
	"FIR_saftyvest_orange",
	
//VSM
	"VSM_FAPC_Breacher_AOR1",
	"VSM_FAPC_MG_AOR1",
	"VSM_FAPC_Operator_AOR1",
	"VSM_CarrierRig_Breacher_AOR1",
	"VSM_CarrierRig_Gunner_AOR1",
	"VSM_CarrierRig_Operator_AOR1",
	"VSM_LBT6094_breacher_AOR1",
	"VSM_LBT6094_MG_AOR1",
	"VSM_LBT6094_operator_AOR1",
	"VSM_RAV_Breacher_AOR1",
	"VSM_RAV_MG_AOR1",
	"VSM_RAV_operator_AOR1",
	"VSM_FAPC_Breacher_M81",
	"VSM_FAPC_MG_M81",
	"VSM_FAPC_Operator_M81",
	"VSM_CarrierRig_Breacher_M81",
	"VSM_CarrierRig_Gunner_M81",
	"VSM_CarrierRig_Operator_M81",
	"VSM_LBT6094_breacher_M81",
	"VSM_LBT6094_MG_M81",
	"VSM_LBT6094_operator_M81",
	"VSM_RAV_Breacher_M81",
	"VSM_RAV_MG_M81",
	"VSM_RAV_operator_M81",
	"VSM_FAPC_Breacher_Multicam",
	"VSM_FAPC_MG_Multicam",
	"VSM_FAPC_Operator_Multicam",
	"VSM_CarrierRig_Breacher_Multicam",
	"VSM_CarrierRig_Gunner_Multicam",
	"VSM_CarrierRig_Operator_Multicam",
	"VSM_LBT6094_breacher_Multicam",
	"VSM_LBT6094_MG_Multicam",
	"VSM_LBT6094_operator_Multicam",
	"VSM_RAV_Breacher_Multicam",
	"VSM_RAV_MG_Multicam",
	"VSM_RAV_operator_Multicam",
	"VSM_FAPC_Breacher_OGA",
	"VSM_FAPC_MG_OGA",
	"VSM_FAPC_Operator_OGA",
	"VSM_CarrierRig_Breacher_OGA",
	"VSM_CarrierRig_Gunner_OGA",
	"VSM_CarrierRig_Operator_OGA",
	"VSM_LBT6094_breacher_OGA",
	"VSM_LBT6094_MG_OGA",
	"VSM_LBT6094_operator_OGA",
	"VSM_FAPC_Breacher_OGA_OD",
	"VSM_FAPC_MG_OGA_OD",
	"VSM_FAPC_Operator_OGA_OD",
	"VSM_CarrierRig_Breacher_OGA_OD",
	"VSM_CarrierRig_Gunner_OGA_OD",
	"VSM_CarrierRig_Operator_OGA_OD",
	"VSM_LBT6094_breacher_OGA_OD",
	"VSM_LBT6094_MG_OGA_OD",
	"VSM_LBT6094_operator_OGA_OD",
	"VSM_RAV_Breacher_OGA_OD",
	"VSM_RAV_MG_OGA_OD",
	"VSM_RAV_operator_OGA_OD",
	"VSM_RAV_Breacher_OGA",
	"VSM_RAV_MG_OGA",
	"VSM_RAV_operator_OGA",
	"VSM_OGA_Vest_1",
	"VSM_OGA_OD_Vest_1",
	"VSM_OGA_Vest_2",
	"VSM_OGA_OD_Vest_2",
	"VSM_OGA_Vest_3",
	"VSM_OGA_OD_Vest_3",
	"dr_Alpinefacp_br",
	"dr_Alpinefacp_mg",
	"dr_Alpinefacp_op",
	"dr_Alpinelbt_br",
	"dr_Alpinelbt_mg",
	"dr_Alpinelbt_op",
	"dr_Alpinepar_br",
	"dr_Alpinepar_mg",
	"dr_Alpinepar_op",
	"LBT_1961_Alpine",
	"dr_BLKfacp_br",
	"dr_BLKfacp_mg",
	"dr_BLKfacp_op",
	"dr_BLKlbt_br",
	"dr_BLKlbt_mg",
	"dr_BLKlbt_op",
	"dr_BLKpar_br",
	"dr_BLKpar_mg",
	"dr_BLKpar_op",
	"CarrieRrig_Breacher_Alpine",
	"CarrieRrig_Gunner_Alpine",
	"CarrieRrig_Operator_Alpine",

// MILGP Vests / Uniforms
	
	// MILGP JPC Assaulter
	"milgp_v_jpc_assaulter_belt_aor1_aor1_aor1",
	"milgp_v_jpc_assaulter_belt_aor1_cb_cb",
	"milgp_v_jpc_assaulter_belt_aor1_mcar_mcar",
	"milgp_v_jpc_assaulter_belt_blk_mcb_mcb",
	"milgp_v_jpc_assaulter_belt_mcb_mcb_mcb",
	"milgp_v_jpc_assaulter_belt_cb_cb_cb",
	"milgp_v_jpc_assaulter_belt_cb_mc_mc",
	"milgp_v_jpc_assaulter_belt_mc_mc_mc",
	"milgp_v_jpc_assaulter_belt_mc_cb_cb",
	"milgp_v_jpc_assaulter_belt_mct_mct_mct",
	"milgp_v_jpc_assaulter_belt_rgr_rgr_rgr",
	"milgp_v_jpc_assaulter_belt_wht_wht_wht",
	
	// MILGP JPC Grenadier
	"milgp_v_jpc_grenadier_belt_aor1_aor1_aor1",
	"milgp_v_jpc_grenadier_belt_aor1_cb_cb",
	"milgp_v_jpc_grenadier_belt_aor1_mc_mc",
	"milgp_v_jpc_grenadier_belt_blk_mcb_mcb",
	"milgp_v_jpc_grenadier_belt_cb_cb_cb",
	"milgp_v_jpc_grenadier_belt_cb_mc_mc",
	"milgp_v_jpc_grenadier_belt_mc_mc_mc",
	"milgp_v_jpc_grenadier_belt_mc_tan_tan",
	"milgp_v_jpc_grenadier_belt_mcb_mcb_mcb",
	"milgp_v_jpc_grenadier_belt_mct_mct_mct",
	"milgp_v_jpc_grenadier_belt_rgr_rgr_rgr",
	"milgp_v_jpc_grenadier_belt_wht_wht_wht",

	// MILGP JPC Heavy Gunner
	"milgp_v_jpc_hgunner_belt_aor1_aor1_aor1",
	"milgp_v_jpc_hgunner_belt_aor1_cb_cb",
	"milgp_v_jpc_hgunner_belt_aor1_mc_mc",
	"milgp_v_jpc_hgunner_belt_blk_mcb_mcb",
	"milgp_v_jpc_hgunner_belt_cb_cb_cb",
	"milgp_v_jpc_hgunner_belt_cb_mc_mc",
	"milgp_v_jpc_hgunner_belt_mc_mc_mc",
	"milgp_v_jpc_hgunner_belt_mc_tan_tan",
	"milgp_v_jpc_hgunner_belt_mcb_mcb_mcb",
	"milgp_v_jpc_hgunner_belt_mct_mct_mct",
	"milgp_v_jpc_hgunner_belt_rgr_rgr_rgr",
	"milgp_v_jpc_hgunner_belt_wht_wht_wht",
	
	// MILGP JPC Marksman
	"milgp_v_jpc_marksman_belt_aor1_aor1_aor1",
	"milgp_v_jpc_marksman_belt_aor1_cb_cb",
	"milgp_v_jpc_marksman_belt_aor1_mc_mc",
	"milgp_v_jpc_marksman_belt_blk_mcb_mcb",
	"milgp_v_jpc_marksman_belt_cb_cb_cb",
	"milgp_v_jpc_marksman_belt_cb_mc_mc",
	"milgp_v_jpc_marksman_belt_mc_mc_mc",
	"milgp_v_jpc_marksman_belt_mc_tan_tan",
	"milgp_v_jpc_marksman_belt_mcb_mcb_mcb",
	"milgp_v_jpc_marksman_belt_mct_mct_mct",
	"milgp_v_jpc_marksman_belt_rgr_rgr_rgr",
	"milgp_v_jpc_marksman_belt_wht_wht_wht",
	
	// MILGP JPC Medic
	"milgp_v_jpc_medic_aor1_aor1_aor1",
	"milgp_v_jpc_medic_belt_belt_aor1_cb_cb",
	"milgp_v_jpc_medic_belt_aor1_mc_mc",
	"milgp_v_jpc_medic_belt_blk_mcb_mcb",
	"milgp_v_jpc_medic_belt_cb_cb_cb",
	"milgp_v_jpc_medic_belt_cb_mc_mc",
	"milgp_v_jpc_medic_belt_mc_mc_mc",
	"milgp_v_jpc_medic_belt_mc_tan_tan",
	"milgp_v_jpc_medic_belt_mcb_mcb_mcb",
	"milgp_v_jpc_medic_belt_mct_mct_mct",
	"milgp_v_jpc_medic_belt_rgr_rgr_rgr",
	"milgp_v_jpc_medic_belt_wht_wht_wht",
	
	// MILGP JPC Teamleader
	"milgp_v_jpc_teamleader_belt_aor1_aor1_aor1",
	"milgp_v_jpc_teamleader_belt_aor1_cb_cb",
	"milgp_v_jpc_teamleader_belt_aor1_mc_mc",
	"milgp_v_jpc_teamleader_belt_blk_mcb_mcb",
	"milgp_v_jpc_teamleader_belt_cb_cb_cb",
	"milgp_v_jpc_teamleader_belt_cb_mc_mc",
	"milgp_v_jpc_teamleader_belt_mc_mc_mc",
	"milgp_v_jpc_teamleader_belt_mc_tan_tan",
	"milgp_v_jpc_teamleader_belt_mcb_mcb_mcb",
	"milgp_v_jpc_teamleader_belt_mct_mct_mct",
	"milgp_v_jpc_teamleader_belt_rgr_rgr_rgr",
	"milgp_v_jpc_teamleader_belt_wht_wht_wht",

	//MilGP MMAC Assaulter
	"milgp_v_mmac_assaulter_belt_aor1_aor1_aor1",
	"milgp_v_mmac_assaulter_belt_aor1_cb_cb",
	"milgp_v_mmac_assaulter_belt_aor1_mc_mc",
	"milgp_v_mmac_assaulter_belt_blk_mcb_mcb",
	"milgp_v_mmac_assaulter_belt_cb_cb_cb",
	"milgp_v_mmac_assaulter_belt_cb_mc_mc",
	"milgp_v_mmac_assaulter_belt_mc_mc_mc",
	"milgp_v_mmac_assaulter_belt_mc_tan_tan",
	"milgp_v_mmac_assaulter_belt_rgr_rgr_rgr",
	"milgp_v_mmac_assaulter_belt_rgr_mcb_mcb",
	"milgp_v_mmac_assaulter_belt_wht_wht_wht",

	//MilGP MMAC Grenadier
	"milgp_v_mmac_grenadier_belt_aor1_aor1_aor1",
	"milgp_v_mmac_grenadier_belt_aor1_cb_cb",
	"milgp_v_mmac_grenadier_belt_aor1_mc_mc",
	"milgp_v_mmac_grenadier_belt_blk_mcb_mcb",
	"milgp_v_mmac_grenadier_belt_cb_cb_cb",
	"milgp_v_mmac_grenadier_belt_cb_mc_mc",
	"milgp_v_mmac_grenadier_belt_mc_mc_mc",
	"milgp_v_mmac_grenadier_belt_mc_tan_tan",
	"milgp_v_mmac_grenadier_belt_rgr_rgr_rgr",
	"milgp_v_mmac_grenadier_belt_rgr_mcb_mcb",
	"milgp_v_mmac_grenadier_belt_wht_wht",

	//MilGP MMAC Heavy Gunner
	"milgp_v_mmac_hgunner_belt_aor1_aor1_aor1",
	"milgp_v_mmac_hgunner_belt_aor1_cb_cb",
	"milgp_v_mmac_hgunner_belt_aor1_mc_mc",
	"milgp_v_mmac_hgunner_belt_blk_mcb_mcb",
	"milgp_v_mmac_hgunner_belt_cb_cb_cb",
	"milgp_v_mmac_hgunner_belt_cb_mc_mc",
	"milgp_v_mmac_hgunner_belt_mc_mc_mc",
	"milgp_v_mmac_hgunner_belt_mc_tan_tan",
	"milgp_v_mmac_hgunner_belt_rgr_rgr_rgr",
	"milgp_v_mmac_hgunner_belt_rgr_mcb_mcb",
	"milgp_v_mmac_hgunner_belt_wht_wht_wht",

	//MilGP MMAC Marksman
	"milgp_v_mmac_marksman_belt_aor1_aor1_aor1",
	"milgp_v_mmac_marksman_belt_aor1_cb_cb",
	"milgp_v_mmac_marksman_belt_aor1_mc_mc",
	"milgp_v_mmac_marksman_belt_blk_mcb_mcb",
	"milgp_v_mmac_marksman_belt_cb_cb_cb",
	"milgp_v_mmac_marksman_belt_cb_mc_mc",
	"milgp_v_mmac_marksman_belt_mc_mc_mc",
	"milgp_v_mmac_marksman_belt_mc_tan_tan",
	"milgp_v_mmac_marksman_belt_rgr_rgr_rgr",
	"milgp_v_mmac_marksman_belt_rgr_mcb_mcb",
	"milgp_v_mmac_marksman_belt_wht_wht_wht",

	//MilGP MMAC Medic
	"milgp_v_mmac_medic_belt_aor1_aor1_aor1",
	"milgp_v_mmac_medic_belt_aor1_cb_cb",
	"milgp_v_mmac_medic_belt_aor1_mc_mc",
	"milgp_v_mmac_medic_belt_blk_mcb_mcb"
	"milgp_v_mmac_medic_belt_cb_cb_cb",
	"milgp_v_mmac_medic_belt_cb_mc_mc",
	"milgp_v_mmac_medic_belt_mc_mc_mc",
	"milgp_v_mmac_medic_belt_mc_tan_tan",
	"milgp_v_mmac_medic_belt_rgr_rgr_rgr",
	"milgp_v_mmac_medic_belt_rgr_mcb_mcb",
	"milgp_v_mmac_medic_belt_wht_wht_wht",


	//MilGP MMAC Team Leader
	"milgp_v_mmac_teamleader_belt_aor1_aor1_aor1",
	"milgp_v_mmac_teamleader_belt_aor1_cb_cb",
	"milgp_v_mmac_teamleader_belt_aor1_mc_mc",
	"milgp_v_mmac_teamleader_belt_blk_mcb_mcb",
	"milgp_v_mmac_teamleader_belt_cb_cb_cb",
	"milgp_v_mmac_teamleader_belt_cb_mc_mc",
	"milgp_v_mmac_teamleader_belt_mc_mc_mc",
	"milgp_v_mmac_teamleader_belt_mc_tan_tan",
	"milgp_v_mmac_teamleader_belt_rgr_rgr_rgr",
	"milgp_v_mmac_teamleader_belt_rgr_mcb_mcb",
	"milgp_v_mmac_teamleader_belt_wht_wht_wht"

];
